services:
#  db:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: todo-db
#    restart: always
#    ports:
#      - "5432:5432"
#    expose:
#      - "5432"
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
  backend:
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json
          target: /app/package.json
        - action: sync+restart
          path: ./prisma
          target: /app/prisma
    build:
      context: .
      dockerfile: Dockerfile
      target: todo-backend
    command: npm start
    ports:
      - "8000:8000"
      - "5555:5555"
    expose:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
#    depends_on:
#      - db

#volumes:
#    postgres-data: